# Generated by Django 4.1.7 on 2023-04-20 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 17, 56, 47, 766411), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 17, 56, 47, 766411), verbose_name='last login'),
        ),
    ]
